#!/usr/bin/env zsh

eval "$(/opt/homebrew/bin/brew shellenv)"
# Completions for brew.
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

GPG_TTY=$(tty)
export GPG_TTY

# Binaries from pipx.
export PATH="$PATH:/Users/rengabkg/.local/bin"